<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Penalty extends Model
{
    use HasFactory;

    protected $fillable = [
        'student_id',
        'installment_id',
        'penalty_type',
        'days_delayed',
        'penalty_rate',
        'penalty_amount',
        'applied_date',
        'status',
        'remarks',
    ];

    protected function casts(): array
    {
        return [
            'penalty_rate' => 'decimal:2',
            'penalty_amount' => 'decimal:2',
            'applied_date' => 'date',
        ];
    }

    /**
     * Get the student that owns this penalty
     */
    public function student(): BelongsTo
    {
        return $this->belongsTo(Student::class);
    }

    /**
     * Get the installment associated with this penalty
     */
    public function installment(): BelongsTo
    {
        return $this->belongsTo(Installment::class);
    }

    /**
     * Check if penalty is auto-generated
     */
    public function isAutoGenerated(): bool
    {
        return $this->penalty_type === 'auto';
    }
}

